#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = -IC:\\Program\ Files\ (x86)\\CodeBlocks\\SDL-1.2.14\\include
CFLAGS = -Wall
RESINC = 
LIBDIR = -LC:\\Program\ Files\ (x86)\\CodeBlocks\\SDL-1.2.14\\lib
LIB = -lmingw32 -lSDLmain SDL.dll -luser32 -lgdi32 -lwinmm -ldxguid C:\\Program\ Files\ (x86)\\CodeBlocks\\SDL-1.2.14\\lib\\SDL_image.lib C:\\Program\ Files\ (x86)\\CodeBlocks\\SDL-1.2.14\\lib\\SDL_ttf.lib
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
OUT_DEBUG = bin\\Debug\\Muhaha.exe

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\Muhaha.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\\VerifFonctions.o $(OBJDIR_DEBUG)\\collisions.o $(OBJDIR_DEBUG)\\dessins.o $(OBJDIR_DEBUG)\\g_souris.o $(OBJDIR_DEBUG)\\interface.o $(OBJDIR_DEBUG)\\main.o $(OBJDIR_DEBUG)\\piles.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\VerifFonctions.o $(OBJDIR_RELEASE)\\collisions.o $(OBJDIR_RELEASE)\\dessins.o $(OBJDIR_RELEASE)\\g_souris.o $(OBJDIR_RELEASE)\\interface.o $(OBJDIR_RELEASE)\\main.o $(OBJDIR_RELEASE)\\piles.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG) md $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\VerifFonctions.o: VerifFonctions.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c VerifFonctions.c -o $(OBJDIR_DEBUG)\\VerifFonctions.o

$(OBJDIR_DEBUG)\\collisions.o: collisions.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c collisions.c -o $(OBJDIR_DEBUG)\\collisions.o

$(OBJDIR_DEBUG)\\dessins.o: dessins.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c dessins.c -o $(OBJDIR_DEBUG)\\dessins.o

$(OBJDIR_DEBUG)\\g_souris.o: g_souris.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c g_souris.c -o $(OBJDIR_DEBUG)\\g_souris.o

$(OBJDIR_DEBUG)\\interface.o: interface.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c interface.c -o $(OBJDIR_DEBUG)\\interface.o

$(OBJDIR_DEBUG)\\main.o: main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.c -o $(OBJDIR_DEBUG)\\main.o

$(OBJDIR_DEBUG)\\piles.o: piles.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c piles.c -o $(OBJDIR_DEBUG)\\piles.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) -mwindows $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\VerifFonctions.o: VerifFonctions.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c VerifFonctions.c -o $(OBJDIR_RELEASE)\\VerifFonctions.o

$(OBJDIR_RELEASE)\\collisions.o: collisions.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c collisions.c -o $(OBJDIR_RELEASE)\\collisions.o

$(OBJDIR_RELEASE)\\dessins.o: dessins.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c dessins.c -o $(OBJDIR_RELEASE)\\dessins.o

$(OBJDIR_RELEASE)\\g_souris.o: g_souris.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c g_souris.c -o $(OBJDIR_RELEASE)\\g_souris.o

$(OBJDIR_RELEASE)\\interface.o: interface.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c interface.c -o $(OBJDIR_RELEASE)\\interface.o

$(OBJDIR_RELEASE)\\main.o: main.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.c -o $(OBJDIR_RELEASE)\\main.o

$(OBJDIR_RELEASE)\\piles.o: piles.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c piles.c -o $(OBJDIR_RELEASE)\\piles.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

